config/routes.rb
Rails.application.routes.draw do
  resources :consulta do
    post :leer, on: :member
  end
  
  resources :investigadors
  resources :cros
  resources :areas
  resources :laboratorios
  resources :estudios
  resources :especialidads
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "estudios#index"
end

app/models/investigador.rb
class Investigador < ApplicationRecord
  validates :nombre, presence: true
  validates :nombre, uniqueness: true
end

app/controllers/investigadors_controller.rb
class InvestigadorsController < ApplicationController
  before_action :set_investigador, only: %i[ show update destroy ]

  # GET /investigadors or /investigadors.json
  def index
    @investigadors = Investigador.all
  end

  # GET /investigadors/1 or /investigadors/1.json
  def show
  end

  # GET /investigadors/new
  def new
    @investigador = Investigador.new
  end

  # POST /investigadors or /investigadors.json
  def create
    @investigador = Investigador.new(investigador_params)

    respond_to do |format|
      if @investigador.save
        format.html { redirect_to @investigador, notice: "Investigador was successfully created." }
        format.json { render :show, status: :created, location: @investigador }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @investigador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investigadors/1 or /investigadors/1.json
  def update
    respond_to do |format|
      if @investigador.update(investigador_params)
        format.html { redirect_to @investigador, notice: "Investigador was successfully updated." }
        format.json { render :show, status: :ok, location: @investigador }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @investigador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investigadors/1 or /investigadors/1.json
  def destroy
    @investigador.destroy
    respond_to do |format|
      format.html { redirect_to investigadors_url, notice: "Investigador was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_investigador
      @investigador = Investigador.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def investigador_params
      params.require(:investigador).permit(:nombre)
    end
end

app/helpers/investigadors_helper.rb
module InvestigadorsHelper
end

app/views/investigadors/_form.html.erb
<%= form_with(model: investigador, local: true) do |form| %>
  <% if investigador.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% investigador.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="regulatorio_form">
    <p id="notice"><%= notice %></p>
    <div class="form-group">
      <%= form.label :nombre_investigador %>
      <%= form.text_field :nombre, class: 'form-control'%>
    </div>
  </div>
  <div class="regulatorio_form">
    <button type="submit" class="btn btn-secondary">Guardar</button>
  </div>
<% end %>

app/views/investigadors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Investigadors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @investigadors.each do |investigador| %>
      <tr>
        <td><%= link_to 'Show', investigador %></td>
        <td><%= link_to 'Edit', edit_investigador_path(investigador) %></td>
        <td><%= link_to 'Destroy', investigador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Investigador', new_investigador_path %>

app/views/investigadors/new.html.erb
<%= render 'form', investigador: @investigador %>

app/views/investigadors/show.html.erb
<%= render 'form', investigador: @investigador %>