config/routes.rb
Rails.application.routes.draw do
  resources :consulta do
    post :leer, on: :member
  end
  
  resources :investigadors
  resources :cros
  resources :areas
  resources :laboratorios
  resources :estudios
  resources :especialidads
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "estudios#index"
end

app/models/cro.rb
class Cro < ApplicationRecord
  validates :nombre, presence: true
  validates :nombre, uniqueness: true
end

app/controllers/cros_controller.rb
class CrosController < ApplicationController
  before_action :set_cro, only: %i[ show update destroy ]

  # GET /cros or /cros.json
  def index
    @cros = Cro.all
  end

  # GET /cros/1 or /cros/1.json
  def show
  end

  # GET /cros/new
  def new
    @cro = Cro.new
  end

  # POST /cros or /cros.json
  def create
    @cro = Cro.new(cro_params)

    respond_to do |format|
      if @cro.save
        format.html { redirect_to @cro, notice: "Cro was successfully created." }
        format.json { render :show, status: :created, location: @cro }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cros/1 or /cros/1.json
  def update
    respond_to do |format|
      if @cro.update(cro_params)
        format.html { redirect_to @cro, notice: "Cro was successfully updated." }
        format.json { render :show, status: :ok, location: @cro }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cros/1 or /cros/1.json
  def destroy
    @cro.destroy
    respond_to do |format|
      format.html { redirect_to cros_url, notice: "Cro was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cro
      @cro = Cro.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cro_params
      params.require(:cro).permit(:nombre)
    end
end

app/helpers/cros_helper.rb
module CrosHelper
end

app/views/cros/_form.html.erb
<%= form_with(model: cro, local: true) do |form| %>
  <% if cro.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% cro.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="regulatorio_form">
    <p id="notice"><%= notice %></p>
    <div class="form-group">
      <%= form.label :nombre_cro %>
      <%= form.text_field :nombre, class: 'form-control'%>
    </div>
  </div>
  <div class="regulatorio_form">
    <button type="submit" class="btn btn-secondary">Guardar</button>
  </div>
<% end %>

app/views/cros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cros</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cros.each do |cro| %>
      <tr>
        <td><%= link_to 'Show', cro %></td>
        <td><%= link_to 'Edit', edit_cro_path(cro) %></td>
        <td><%= link_to 'Destroy', cro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cro', new_cro_path %>

app/views/cros/new.html.erb
<%= render 'form', cro: @cro %>

app/views/cros/show.html.erb
<%= render 'form', cro: @cro %>