config/routes.rb
Rails.application.routes.draw do
  resources :consulta do
    post :leer, on: :member
  end
  
  resources :investigadors
  resources :cros
  resources :areas
  resources :laboratorios
  resources :estudios
  resources :especialidads
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: "estudios#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Regulatorio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-dark bg-dark" style="-webkit-print-color-adjust: exact">
        <h2 style="color: white">
          Regulatorio
        <h2>
      </nav>
      <nav class="navbar-dark bg-dark regulatorio_menu">
        <%= link_to 'Listado Estudios', root_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nuevo Estudio', new_estudio_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nueva Area', new_area_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nueva Especialidad', new_especialidad_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nuevo Laboratorio', new_laboratorio_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nuevo Cro', new_cro_path, class: 'btn btn-secondary' %>
        <%= link_to 'Nuevo Investigador', new_investigador_path, class: 'btn btn-secondary' %>
      </nav>
        <%= yield %>
    </body>
</html>